#!/usr/bin/env bash
# Compiles every circuit, writes verification keys, pins inner vk hashes into the aggregators,
# and generates the Solidity verifiers. Idempotent; safe to rerun.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
C="$ROOT/circuits"
OUT="$ROOT/contracts/src/verifiers"
mkdir -p "$OUT"

BATCHES=(64 256 512 1024)
AGGS=("64:2" "1024:4")

pascal() { echo "$1" | awk -F_ '{for(i=1;i<=NF;i++) printf toupper(substr($i,1,1)) substr($i,2)}'; }

gen_verifier() { # pkg
  local pkg="$1" name; name="$(pascal "$pkg")Verifier"
  bb write_solidity_verifier -k "$C/$pkg/target/vk_evm/vk" -o "$OUT/$name.sol" -t evm >/dev/null 2>&1
  # Unique contract name per circuit so several verifiers can live in one Foundry project.
  sed -i '' "s/^contract HonkVerifier is/contract $name is/" "$OUT/$name.sol"
  echo "  verifier  $OUT/$name.sol"
}

for n in "${BATCHES[@]}"; do
  pkg="batch_$n"
  echo "[$pkg]"
  (cd "$C/$pkg" && nargo compile --silence-warnings)
  bb write_vk -b "$C/$pkg/target/$pkg.json" -o "$C/$pkg/target/vk_evm" -t evm >/dev/null 2>&1
  bb write_vk -b "$C/$pkg/target/$pkg.json" -o "$C/$pkg/target/vk_noir-recursive-no-zk" -t noir-recursive-no-zk >/dev/null 2>&1
  gen_verifier "$pkg"
done

for spec in "${AGGS[@]}"; do
  b="${spec%%:*}"; k="${spec##*:}"; pkg="agg_${b}x${k}"
  echo "[$pkg]"
  mkdir -p "$C/$pkg/src"
  hash="0x$(xxd -p -c32 "$C/batch_$b/target/vk_noir-recursive-no-zk/vk_hash")"
  cat > "$C/$pkg/Nargo.toml" <<TOML
[package]
name = "$pkg"
type = "bin"
authors = ["Agnij Dutta"]

[dependencies]
zkexpense_lib = { path = "../lib" }
TOML
  cat > "$C/$pkg/src/main.nr" <<NR
// GENERATED by scripts/build.sh. Aggregates $k proofs of circuits/batch_$b into one report.
use zkexpense_lib::{aggregate, Inner, INNER_VK_LEN, Policy, Report};

global K: u32 = $k;
global BATCH: u32 = $b;
// Poseidon2 vk hash of circuits/batch_$b (bb write_vk -t noir-recursive-no-zk).
global PINNED_VK_HASH: Field = $hash;

fn main(
    policy: pub Policy,
    inner_vk: [Field; INNER_VK_LEN],
    inner_vk_hash: Field,
    inners: [Inner; K],
    total_blind: Field,
) -> pub Report {
    aggregate(policy, BATCH, inner_vk, inner_vk_hash, PINNED_VK_HASH, inners, total_blind)
}
NR
  (cd "$C/$pkg" && nargo compile --silence-warnings)
  bb write_vk -b "$C/$pkg/target/$pkg.json" -o "$C/$pkg/target/vk_evm" -t evm >/dev/null 2>&1
  gen_verifier "$pkg"
done
echo "done"
